---
title: "adsorption_markdown"
author: "Kaizad Patel"
date: "10/12/2019"
output: html_document
---

## R Markdown


```{r input, echo=FALSE,echo=FALSE,warning=FALSE,message=FALSE}
source("0-packages.R")

# INPUT
meta_elements = read.csv(ELEMENTS)
hcoc = read.csv(HCOC)

relabund = read.csv(RELATIVE_ABUND)# <- "fticr/fticr_relative_abundance.csv"
elements = read.csv(SUMMARY_ELEMENTS)# <- "fticr/fticr_summary_elements.csv"

percentile = read.csv(PERCENTILE)
fentonloss = read.csv(FENTON_LOSS)
sorbed = read.csv(GOETHITE_ADSORPTION)
sorbed_relabund = read.csv(GOETHITE_RELABUND)
```

# Native SOM and the Fenton reaction
## summary tables
```{r summary table, echo=FALSE,warning=FALSE,message=FALSE}

elements %>% 
  dplyr::mutate(sp = paste(Forest, Treatment),
                val = paste(avg)) %>% 
  select(element, sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")

relabund%>% 
  ungroup %>% 
  dplyr::mutate(sp = paste(Forest, Fenton),
                val = paste(relabund_hsd)) %>% 
  select(Class,sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```

----

## van krevelens

```{r native van krev, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="native SOM", fig.width=12, fig.height=12,fig.path = "images/"}
percentile %>% 
  mutate(Treatment=factor(Treatment, levels = c("PreFenton","PostFenton")))->
  percentile

gg_vankrev(percentile, aes(x=OC,y=HC,color=perc))+
  scale_color_brewer(palette = "Reds")+
  facet_grid(Treatment~Forest)+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_bw()+
  theme_kp()

```

----
## fenton 

1. fenton loss/gained
```{r fenton, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="native SOM", fig.width=8, fig.height=8,fig.path = "images/"}

gg_vankrev(fentonloss[!fentonloss$loss=="conserved",], aes(x = OC, y = HC, color = loss))+
  scale_color_brewer(palette = "Dark2")+
  theme_bw()+
  theme_kp()
```


---

2. fenton vs. oxygens

```{r fenton_oxygen, eval=TRUE,echo=FALSE, warning=FALSE,message=FALSE,fig.cap="native SOM", fig.width=8, fig.height=8,fig.path = "images/"}
fenton_el = merge(fentonloss, meta_elements, by = "Mass", all.x=TRUE)

# create a new column assigning -ve value to lost abundance
fenton_el %>% 
  mutate(rel_abund_new = ifelse(loss == "gained",rel_abund,-1*rel_abund))->
  fenton_el

fenton_el %>% 
  group_by(loss,O) %>% 
  dplyr::summarize(total = sum(rel_abund)) %>% 
  ungroup() %>% 
  group_by(loss) %>% 
  dplyr::mutate(median = median(O))->
  loss_summary

  
ggplot(fenton_el[!fenton_el$loss=="conserved",], aes(x = as.factor(O), y = rel_abund_new, fill=loss))+
  geom_bar(stat = "identity", alpha=0.6)+
  scale_fill_brewer(palette="Dark2")+
  
  scale_x_discrete(breaks = c("0", "5","10","15","20","25","30"))+
  scale_y_continuous(breaks = seq(-8, 8, by = 4))+
  ylab("% of total intensity")+
  xlab("number of O")+

  geom_segment(x = 13.5, y = 0, xend = 13.5, yend = 7.5,color="black",linetype="longdash")+
  geom_segment(x = 10.5, y = 0, xend = 10.5, yend = -7.5,color="black",linetype="longdash")+
  annotate("text", label = "median 13.5", x = 13.5, y = 7.8)+ 
  annotate("text", label = "median 10.5", x = 10.5, y = -7.8)+ 

  
  
  theme_bw()+
  theme_kp()

```

----

# goethite

1. sorption fractionation

```{r goethite_vk, eval=TRUE,echo=FALSE, warning=FALSE,message=FALSE,fig.cap="native SOM", fig.width=12, fig.height=5,fig.path = "images/"}

# set order of levels
sorbed %>% 
  mutate(sorption_frac = factor(sorption_frac, levels = c("most sorbed",
                                                        "more sorbed",
                                                        "sorbed",
                                                        "minimal change",
                                                        "unbound",
                                                        "more unbound",
                                                        "most unbound")),
         fenton = factor(fenton, levels = c("PreFenton","PostFenton"))
         )->
  sorbed

gg_vankrev(sorbed, aes(x = OC, y = HC, color=sorption_frac))+
  scale_color_brewer(palette = "PuOr")+
  facet_wrap(~fenton)+
  theme_bw()+
  theme_kp()+
  theme(legend.position = "right")

```

2. contribution of groups
```{r sorbed_groups, eval=TRUE,echo=FALSE, warning=FALSE,message=FALSE,fig.cap="native SOM", fig.width=9, fig.height=7,fig.path = "images/"}
sorbed_relabund %>% 
  group_by(fenton,Class, sorption_frac) %>% 
  dplyr::summarise(relabund = mean(relabund)) %>% 
  ungroup %>% 
  dplyr::mutate(fenton = factor(fenton, levels = c("PreFenton","PostFenton")), 
                  Class = factor(Class, levels = c("Condensed Ar",
                                                 "Aromatic",
                                                 "Lignin-like",
                                                 "Carbohydrate-like",
                                                 "Aliphatic-noN",
                                                 "Aliphatic+N")))->
  sorbed_relabund2


ggplot(sorbed_relabund2, aes(x=Class, y=relabund, fill=sorption_frac))+
  geom_bar(stat="identity", position = position_dodge(width=0.7),width=0.5, alpha=1,color="black")+
#  scale_fill_manual(values = c("#B35806","#542788"))+
  scale_fill_manual(values = c("#F1A340","#998EC3"))+
  
  ylab("% of total intensity")+
  xlab("")+

  facet_wrap(~fenton)+
  theme_bw()+
  theme_kp()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, face="plain", size = 12))

```


