---
title: "adsorption_markdown"
author: "Kaizad Patel"
output: html_document
---

Run: `r Sys.Date()`


```{r knitrsetup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/"
                      )

library(wesanderson)
```

```{r input}
source("0-packages.R")

# INPUT
meta_elements = read.csv(ELEMENTS)
hcoc = read.csv(HCOC)

relabund = read.csv(RELATIVE_ABUND)# <- "fticr/fticr_relative_abundance.csv"
elements = read.csv(SUMMARY_ELEMENTS)# <- "fticr/fticr_summary_elements.csv"

percentile = read.csv(PERCENTILE)
fentonloss = read.csv(FENTON_LOSS)
sorbed = read.csv(GOETHITE_ADSORPTION)
sorbed_relabund = read.csv(GOETHITE_RELABUND)
```

# Native SOM and the Fenton reaction
## summary tables
```{r summary table}

elements %>% 
  dplyr::mutate(sp = paste(Forest, Treatment),
                val = paste(avg)) %>% 
  select(element, sp, val) %>% 
  dplyr::mutate(sp = factor(sp, levels = c("HW PreFenton","HW PostFenton", "SW PreFenton", "SW PostFenton"))) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")

relabund%>% 
  ungroup %>% 
  dplyr::mutate(sp = paste(Forest, Fenton),
                val = paste(rel_abund)) %>% 
  select(Class,sp, val) %>% 
  dplyr::mutate(sp = factor(sp, levels = c("HW PreFenton","HW PostFenton", "SW PreFenton", "SW PostFenton")), 
                  Class = factor(Class, levels = c("Condensed Ar",
                                                 "Aromatic",
                                                 "Lignin-like",
                                                 "Carbohydrate-like",
                                                 "Aliphatic-noN",
                                                 "Aliphatic+N"))) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```


## van krevelen: native SOM

```{r native_van_krev, fig.cap="native SOM", fig.width=9, fig.height=5}
percentile %>% 
  mutate(Treatment=factor(Treatment, levels = c("PreFenton","PostFenton")))->
  percentile

gg_vankrev(percentile[percentile$Treatment=="PreFenton",], aes(x=OC,y=HC,color=perc))+
  scale_color_brewer(palette = "Blues")+
  facet_wrap(~Forest)+
  #guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_kp()

```

## van krevelen: Fenton

```{r fenton_van_krev, fig.cap="fenton SOM", fig.width=9, fig.height=5}
gg_vankrev(percentile[percentile$Treatment=="PostFenton",], aes(x=OC,y=HC,color=perc))+
  scale_color_brewer(palette = "Reds")+
  facet_wrap(~Forest)+
  #guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_kp()

```



## fenton 

1. fenton loss/gained
```{r fenton, fig.cap="fenton loss", fig.width=5, fig.height=5}

gg_vankrev(fentonloss[!fentonloss$loss=="conserved",], aes(x = OC, y = HC, color = loss, shape=loss))+
  scale_shape_manual(values = c(16,1))+
  scale_color_brewer(palette = "Dark2")+
  theme_kp()
```


2. fenton vs. oxygens

```{r fenton_oxygen2, fig.cap="fenton  vs. no. of oxygens", fig.width=5, fig.height=5}
fenton_el = merge(fentonloss, meta_elements, by = "Mass", all.x=TRUE)

fenton_el %>% 
  group_by(loss,O) %>% 
  dplyr::summarize(counts = n()) %>% 
  dplyr::mutate(counts = as.numeric(counts))%>% 
  ungroup() %>% 
  group_by(loss) %>% 
  dplyr::mutate(cumsum = cumsum(counts),
                counts2 = if_else(loss == "gained",counts,-1*counts))->
  loss_summary2

ggplot(loss_summary2[!loss_summary2$loss=="conserved",], aes(x=as.factor(O), y=counts2, fill = loss))+
 geom_segment(x = 13.5, y = 0, xend = 13.5, yend = 140,color="black",linetype="longdash")+
  geom_segment(x = 8.5, y = 0, xend = 8.5, yend = -190,color="black",linetype="longdash")+
  annotate("text", label = "median 13", x = 13.5, y = 150)+ 
  annotate("text", label = "median 8", x = 8.5, y = -200)+
  
  geom_bar(stat = "identity", alpha=0.8)+
  scale_fill_brewer(palette="Dark2")+
  
  scale_x_discrete(breaks = c("0", "5","10","15","20","25","30"))+
  ylab("number of peaks")+
  xlab("number of O")+
  
  theme_kp()

```

```{r fenton_2}
fenton_el %>% 
  left_join(class, by = "Mass")-> fenton_el2

ggplot(fenton_el2, aes(x = O, fill = loss))+
  geom_histogram()+
  facet_grid(loss~Class)


master %>% 
  left_join(class, by = "Mass") %>% 
  left_join(meta_elements, by = "Mass")->master2

ggplot(master2, aes(x = O))+
  geom_histogram()+
  facet_grid(Treatment~Class)


```


# goethite

1. sorption fractionation

```{r goethite_vk, fig.cap="native SOM", fig.width=9, fig.height=5}
# set order of levels
sorbed %>% 
  dplyr::mutate(fenton=factor(fenton, levels = c("PreFenton","PostFenton")))->sorbed

gg_vankrev(sorbed[!sorbed$adsorbed=="new",], aes(x = OC, y = HC, color=adsorbed, shape = adsorbed))+
 # scale_color_manual(values = c("#F1A340","#998EC3"))+
 scale_color_manual(values = c("darkblue","grey69"))+
  scale_shape_manual(values = c(16,1))+
  facet_wrap(~fenton)+
  theme_kp()+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))


```

2. contribution of groups
```{r sorbed_groups, fig.cap="", fig.width=9, fig.height=6}
sorbed_relabund %>% 
  group_by(fenton,adsorbed,Class) %>% 
  dplyr::summarise(relabund = mean(relabund)) %>% 
  ungroup %>% 
  dplyr::mutate(fenton = factor(fenton, levels = c("PreFenton","PostFenton")), 
                  Class = factor(Class, levels = c("Condensed Ar",
                                                 "Aromatic",
                                                 "Lignin-like",
                                                 "Carbohydrate-like",
                                                 "Aliphatic-noN",
                                                 "Aliphatic+N")))->
  sorbed_relabund2


ggplot(sorbed_relabund2[!sorbed_relabund2$adsorbed=="new",], aes(x=Class, y=relabund, fill=adsorbed))+
  geom_bar(stat="identity", position = position_dodge(width=0.7),width=0.5, alpha=0.8,color="black",size=0.7)+
#  scale_fill_manual(values = c("#B35806","#542788"))+
#  scale_fill_manual(values = c("#F1A340","#998EC3"))+
  scale_fill_manual(values = c("darkblue","grey80"))+
  
  ylab("% of total abundance")+
  xlab("")+

  facet_wrap(~fenton)+
  theme_bw()+
  theme_kp()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, face="plain", size = 12))

```
