---
title: "4-misc_markdown"
author: "Kaizad Patel"
date: "4/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/"
                      )
source("0-packages.R")
```

calculating NOSC of Fenton-lost and gained molecules

```{r}
fenton_loss = read.csv(FENTON_LOSS)
meta = read.csv(FTICR_META)

loss = fenton_loss %>% 
  filter(loss %in% c("lost", "gained")) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class),  by = "Mass")


ggplot(loss, aes(x = NOSC, color = loss, fill = loss))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(~Forest)

loss_subset = 
  loss %>% 
  filter(Class %in% c("Carbohydrate-like","Lignin-like"))

gg2 = ggplot(loss_subset, aes(x = NOSC, color = loss, fill = loss))+
  geom_histogram(alpha = 0.5, position = "identity")
  #facet_grid(Class~.)

gg1 = 
ggplot(loss_subset)+
  geom_boxplot(aes(y = NOSC,  color = loss),  width = 10)+
  coord_flip()

ggplot(loss_subset)+
  geom_boxplot(aes(x = NOSC, y=80, color = loss),  width = 10)+
  geom_histogram(aes(x = NOSC, color = loss, fill = loss),
                 alpha = 0.5, position = "identity")


library(patchwork)
gg1/gg2+
  plot_layout(heights = c(1,10))

ggplot(loss[loss$Class=="Lignin-like",], aes(x = NOSC, color = loss, fill = loss))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=80, color = loss), fill = "white",  width = 10)

  facet_grid(~Forest)

```

```{r}

fent = read.csv("fticr/fticr_master_hcoc.csv")
fenton = 
  fent %>% 
  filter(Treatment %in% c("PreFenton", "PostFenton")) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class),  by = "Mass")


ggplot(fenton[fenton$Class=="Lignin-like",])+
  geom_boxplot(aes(x = OC, y=150, color = Treatment),  width = 10)+
  geom_histogram(aes(x = OC, color = Treatment, fill = Treatment),
                 alpha = 0.5, position = "identity")


fenton2 = 
  fenton %>% 
  group_by(Mass, Forest, Treatment) %>% 
  dplyr::summarize(n = n()) %>% 
  ungroup %>% 
  group_by(Treatment,Mass) %>% 
  dplyr::summarize(n = n()) %>% 
  ungroup %>% 
  group_by(Treatment, n) %>% 
  dplyr::summarise(count = n())
```



calculating NOSC of adsorbed molecules
```{r}
adsorbed = read.csv(GOETHITE_ADSORPTION)
adsorbed_nosc = adsorbed %>% 
  left_join(dplyr::select(meta, Mass, NOSC),  by = "Mass")

adsorbed_subset = 
  adsorbed_nosc %>% 
  filter(Class %in% c("Carbohydrate-like","Lignin-like"),
         adsorbed %in% c("sorbed"))
  dplyr::mutate(fenton = factor(fenton, levels = c("PreFenton", "PostFenton")))
  

ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(.~Forest)
  
ggplot(adsorbed_subset, aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(Class~Forest)

ggplot(adsorbed_subset, aes(y = NOSC, x = "", color = fenton))+
  geom_boxplot()+
  facet_grid(Class~Forest)


ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=150, color = fenton),  fill = "white", width = 10)+
  ggtitle("adsorbed")

ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=100, color = fenton),  fill = "white", width = 10)+
  ggtitle("adsorbed")+
  facet_wrap(~Class)

ggplot(adsorbed_subset, aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(binwidth = 0.05, alpha = 0.7, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=70, color = fenton),  fill = "white", width = 10)+

  #  ggtitle("adsorbed")+
  
# scale_color_manual(values = c("grey40","darkblue"), guide = guide_legend(reverse=TRUE))+
# scale_fill_manual(values = c("darkblue","black"))+
#scale_fill_discrete(guide = guide_legend(reverse=TRUE))+
#scale_color_discrete(guide = guide_legend(reverse=TRUE))+

  scale_fill_manual(values = soil_palette("redox",2), guide = guide_legend(reverse=TRUE))+
  scale_color_manual(values = soil_palette("redox",2), guide = guide_legend(reverse=TRUE))+
    
  facet_wrap(~Class)+
  theme_kp()
```

Van Krevelen domains
```{r}
gg_vankrev(meta, aes(x = OC, y = HC, color = Class))+
  theme_kp()

gg_vankrev(meta, aes(x = OC, y = HC, color = as.factor(DBE)))
  theme_kp()

gg_vankrev(meta, aes(x = OC, y = HC, color = NOSC))
  theme_kp()

```

adsorbed peaks common to pre and post-Fenton
```{r}
sorbed3 = 
  sorbed %>% 
  filter(adsorbed=="sorbed") %>% 
  group_by(Mass,fenton,adsorbed, HC, OC, Class) %>% 
  dplyr::summarise(n = n())  %>% 
  ungroup %>% 
  group_by(Mass, HC, OC) %>% 
  dplyr::mutate(common="common",
                unique = n(),
                unique2 = case_when(unique==1 ~ fenton,
                                    unique==2 ~ as.factor(common)))
 
  spread(fenton, adsorbed)
  filter(PreFenton=="sorbed") %>% 

  group_by(PostFenton) %>% 
  dplyr::summarise(n = n())



gg_vankrev(sorbed3, aes(x = OC, y = HC, color=unique2))+
 # scale_color_manual(values = c("#F1A340","#998EC3"))+
# scale_color_manual(values = c("grey40","darkblue"))+
  #facet_wrap(~fenton)+
  theme_kp()
  theme(legend.position = "none")
  


```


## combining fenton and goethite
```{r}
# set order of levels
sorbed %>% 
  group_by(Mass,fenton,adsorbed, HC, OC, Class) %>% 
  dplyr::summarise(n = n()) %>% 
  ungroup %>% 
  dplyr::mutate(fenton=factor(fenton, levels = c("PreFenton","PostFenton")))->sorbed

sorbed2 = 
  sorbed %>% 
  left_join(dplyr::select(fentonloss, Mass, Forest, loss), by = c("Mass", "Forest"))





gg_vankrev(sorbed2[sorbed2$adsorbed=="sorbed",], aes(x = OC, y = HC, color=loss))+
 # scale_color_manual(values = c("#F1A340","#998EC3"))+
 #scale_color_manual(values = c("grey40","darkblue"))+
  facet_grid(loss~fenton)+
  theme_kp()
  theme(legend.position = "none")
```