---
title: "adsorption_markdown"
author: "Kaizad Patel"
output: html_document
---

Run: `r Sys.Date()`


```{r knitrsetup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/markdown/"
                      )

library(wesanderson)
# devtools::install_github("kaizadp/soilpalettes")
library(soilpalettes)
```

```{r input}
source("code/0-packages.R")
library(soilpalettes)
# INPUT
meta_elements = read.csv(ELEMENTS)
meta = read.csv(FTICR_META)
hcoc = read.csv(HCOC)
master = read.csv(FTICR_MASTER_LONG)# <- "fticr/fticr_master_long.csv" #
class = read.csv(CLASS)# <- "fticr/meta_class.csv"

relabund = read.csv(RELATIVE_ABUND)# <- "fticr/fticr_relative_abundance.csv"
elements = read.csv(SUMMARY_ELEMENTS)# <- "fticr/fticr_summary_elements.csv"

master_hcoc = read.csv(PERCENTILE)
fentonloss = read.csv(FENTON_LOSS)
sorbed = read.csv(GOETHITE_ADSORPTION)
sorbed_relabund = read.csv(GOETHITE_RELABUND)

```

# Native SOM and the Fenton reaction
## summary tables
```{r summary table}

elements %>% 
  dplyr::mutate(sp = paste(Forest, Treatment),
                val = paste(avg)) %>% 
  select(element, sp, val) %>% 
  dplyr::mutate(sp = factor(sp, levels = c("HW PreFenton","HW PostFenton", "SW PreFenton", "SW PostFenton"))) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")

relabund%>% 
  ungroup %>% 
  dplyr::mutate(sp = paste(Forest, Fenton),
                val = paste(rel_abund)) %>% 
  select(Class,sp, val) %>% 
  dplyr::mutate(sp = factor(sp, levels = c("HW PreFenton","HW PostFenton", "SW PreFenton", "SW PostFenton")), 
                  Class = factor(Class, levels = c("Condensed Ar",
                                                 "Aromatic",
                                                 "Lignin-like",
                                                 "Carbohydrate-like",
                                                 "Aliphatic-noN",
                                                 "Aliphatic+N"))) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")

print("number of peaks")

master %>% 
  group_by(Forest, Treatment) %>% 
  dplyr::summarise(peaks = n()) %>% 
  knitr::kable(align = "r")
  
  
```

## concentrations
```{r}
source("code/4-doc_conc.R")
print("concentrations, mg/L")
conc_summary %>% 
  dplyr::mutate(wsoc_mg_L = paste(round(doc_mg_L,0),"\U00B1",round(doc_se,1))) %>% 
  dplyr::select(Forest, Fenton, wsoc_mg_L) %>% 
  knitr::kable(align = "r")

print("adsorbed C, mg/g goethite")
conc_summary %>% 
  dplyr::mutate(adsorbed = paste(round(adsorbed_mgg,1),"\U00B1",round(adsorbed_se,1))) %>% 
  dplyr::select(Forest, Fenton, adsorbed) %>% 
  knitr::kable(align = "r")  


```


#### van krevelen: native SOM

```{r native_van_krev, fig.cap="native SOM", fig.width=10, fig.height=5, include=FALSE}
master_hcoc %>% 
  mutate(Treatment=factor(Treatment, levels = c("PreFenton","PostFenton")))->
  master_hcoc

gg_vankrev(master_hcoc[master_hcoc$Treatment=="PreFenton",], aes(x=OC,y=HC, color = Treatment))+
  facet_wrap(~Forest)+
  scale_color_manual(values = "dodgerblue1")+
  #guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_kp()+
  theme(legend.position = "none")
```

#### van krevelen: Fenton

```{r fenton_van_krev, fig.cap="fenton SOM", fig.width=10, fig.height=5, include=FALSE}
gg_vankrev(master_hcoc[master_hcoc$Treatment=="PostFenton",], aes(x=OC,y=HC, color = Treatment))+
  facet_wrap(~Forest)+
  scale_color_manual(values = "tomato")+
  theme_kp()+
  theme(legend.position = "none")
```


#### van krevelen: combined 
```{r vk_fenton_trt, fig.width=9, fig.height=5}
master_hcoc %>% 
  mutate(Treatment=factor(Treatment, levels = c("PreFenton","PostFenton")))->
  master_hcoc

gg_vankrev(master_hcoc, aes(x=OC,y=HC, color = Forest))+
  facet_grid(.~Treatment)+
  stat_ellipse(level = 0.95)+
  #scale_color_manual(values = c("dodgerblue1","tomato"))+
  scale_color_manual(values = soil_palette("podzol",2))+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_kp()+
  
  annotate("text", label = "aliphatic", x = 1.1, y = 2.0)+
  annotate("text", label = "lignin-like", x = 1.1, y = 1.0)+
  annotate("text", label = "aromatic", x = 1.1, y = 0.7)+
  annotate("text", label = "condensed \n aromatic", x = 1.1, y = 0.2)

```


## fenton 

```{r fenton_loss, fig.width=5, fig.height=5}

fentonloss2 = fentonloss %>% 
  group_by(Mass, loss) %>% 
  dplyr::summarize(n = n()) %>% 
  left_join(select(meta_elements, Mass,O), by = "Mass") %>% 
  left_join(hcoc, by = "Mass")

gg_loss =
  gg_vankrev(fentonloss2[fentonloss2$loss=="lost"|fentonloss2$loss=="gained",], 
           aes(x = OC, y = HC, color = loss))+
  #scale_shape_manual(values = c(16,1))+
  #scale_color_brewer(palette = "Dark2")+
  stat_ellipse(level = 0.95)+
  scale_color_manual(values = soil_palette("rendoll",2))+

  theme_kp()+
  theme(legend.position = c(0.7, 0.92),
        legend.direction = "horizontal")+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))

gg_loss2 = 
  ggMarginal(gg_loss,groupColour = TRUE,groupFill = TRUE, size = 10)


```

```{r fenton_oxygen2, fig.width=5, fig.height=5}

fentonloss2 %>% 
  group_by(loss,O) %>% 
  dplyr::summarize(counts = n()) %>% 
  dplyr::mutate(counts = as.numeric(counts))%>% 
  ungroup() %>% 
  group_by(loss) %>% 
  dplyr::mutate(cumsum = cumsum(counts),
                counts2 = if_else(loss == "gained",counts,-1*counts))->
  loss_summary2

gg_loss_o =
  ggplot(loss_summary2[loss_summary2$loss=="lost"|loss_summary2$loss=="gained",], 
       aes(x=as.factor(O), y=counts2, fill = loss))+
 geom_segment(x = 13.5, y = 0, xend = 13.5, yend = 140,color="black",linetype="longdash")+
  geom_segment(x = 8.5, y = 0, xend = 8.5, yend = -190,color="black",linetype="longdash")+
  annotate("text", label = "median 13", x = 13.5, y = 150)+ 
  annotate("text", label = "median 8", x = 8.5, y = -200)+
  
  geom_bar(stat = "identity", alpha=0.8)+
  #scale_fill_brewer(palette="Dark2")+
  scale_fill_manual(values = soil_palette("rendoll",2))+

  scale_x_discrete(breaks = c("0", "5","10","15","20","25","30"))+
  ylab("number of peaks")+
  xlab("number of O")+
  
  theme_kp()+
  theme(legend.position = c(0.8, 0.3))+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))


```


```{r fenton_loss_combined, fig.width=9, fig.height=4}
library(patchwork)
gg_loss2 + gg_loss_o

library(cowplot)
plot_grid(gg_loss2, gg_loss_o, labels = c('A', 'B'), label_size = 12, axis = "bl", align = "hv")

```

```{r fenton_2, include=FALSE}
fentonloss2 %>% 
  left_join(class, by = "Mass")-> fenton_el2

ggplot(fenton_el2, aes(x = O, fill = loss))+
  geom_histogram()+
  facet_grid(loss~Class)


master %>% 
  left_join(class, by = "Mass") %>% 
  left_join(meta_elements, by = "Mass")->master2

ggplot(master2, aes(x = O))+
  geom_histogram()+
  facet_grid(Treatment~Class)


```

3. fenton vs. oxygens by class

```{r, include=FALSE}
ggplot(master2[master2$Treatment=="PreFenton"|master2$Treatment=="PostFenton",], 
       aes(x = O, color = Treatment, fill = Treatment))+
  geom_histogram(binwidth = 1, alpha = 0.2, position = "identity")+
  facet_wrap(~Class)

master2 %>% 
  group_by(Mass,Treatment, Class) %>% 
  dplyr::summarise(O = mean(O)) %>% 
  ungroup %>% 
  group_by(Treatment, Class) %>% 
  dplyr::summarise(medianO = median(O)) %>% 
  spread(Treatment, medianO)
```

4. fenton peaks lost

```{r}
fentonloss %>% 
  group_by(Mass,loss) %>% 
  dplyr::summarise(n = n()) %>% 
  na_if(.,"") %>% 
  na.omit() %>% 
  left_join(class, by = "Mass") %>% 
  group_by(loss, Class) %>% 
  dplyr::summarize(count = n()) %>% 
  ungroup %>% 
  select(loss, Class, count) %>% 
  spread(loss, count) %>% 
  knitr::kable(align = "r")  


```


## goethite

### 1. sorption fractionation

```{r goethite_sorbed}
# set order of levels
sorbed2 = 
  sorbed %>% 
  group_by(Mass,fenton,adsorbed, HC, OC, Class) %>% 
  dplyr::summarise(n = n()) %>% 
  ungroup 
  #dplyr::mutate(fenton=factor(fenton, levels = c("PreFenton","PostFenton")))

```

VK - adsorbed and unbound peaks  

```{r sorbed_vk1, fig.width=9, fig.height=5}
gg_vankrev(sorbed2[!sorbed2$adsorbed=="new",], aes(x = OC, y = HC, color=adsorbed))+
 # scale_color_manual(values = c("#F1A340","#998EC3"))+
 scale_color_manual(values = c("grey40","darkblue"))+
  facet_wrap(~fenton)+
  theme_kp()+
  theme(legend.position = c(0.7, 0.92),
        legend.direction = "horizontal")+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))

```

contribution of groups  

```{r sorbed_relabund}
sorbed_relabund %>% 
  group_by(fenton,adsorbed,Class) %>% 
  dplyr::summarise(relabund = mean(relabund)) %>% 
  ungroup %>% 
  dplyr::mutate( #fenton = factor(fenton, levels = c("PreFenton","PostFenton")), 
                  Class = factor(Class, levels = c("Condensed Ar",
                                                 "Aromatic",
                                                 "Lignin-like",
                                                 "Carbohydrate-like",
                                                 "Aliphatic-noN",
                                                 "Aliphatic+N")))->
  sorbed_relabund2
```

```{r sorbed_groups, fig.width=9, fig.height=7, include=FALSE}
ggplot(sorbed_relabund2[!sorbed_relabund2$adsorbed=="new",], aes(x=Class, y=relabund, fill=adsorbed))+
  geom_bar(stat="identity", position = position_dodge(width=0.7),width=0.5,
           alpha=0.8,color="black",size=0.7)+
#  scale_fill_manual(values = c("#B35806","#542788"))+
#  scale_fill_manual(values = c("#F1A340","#998EC3"))+
  scale_fill_manual(values = c("darkblue","grey80"))+
  
  ylab("% of total sorbed peaks")+
  xlab("")+

  facet_wrap(~fenton)+
  theme_bw()+
  theme_kp()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, face="plain", size = 12))

```


### sorbed peaks only


```{r goethite_vk2, fig.width=5, fig.height=5}
# set order of levels
gg_sorbed =
  gg_vankrev(sorbed[sorbed$adsorbed=="sorbed",], aes(x = OC, y = HC, color=fenton))+
 # scale_color_manual(values = c("#F1A340","#998EC3"))+
 #scale_color_manual(values = c("grey40","darkblue"))+
  scale_color_manual(values = soil_palette("redox",2),
                     breaks = c("PreFenton", "PostFenton"))+
  #facet_wrap(~fenton)+
  stat_ellipse()+
  theme_kp()+
  theme(legend.position = c(0.65, 0.92),
        legend.direction = "horizontal")+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))


ggMarginal(gg_sorbed,groupColour = TRUE,groupFill = TRUE, size = 10)

```


```{r goethite_groups2, fig.width=5, fig.height=6}
ggplot(sorbed_relabund2[sorbed_relabund2$adsorbed=="sorbed",], aes(x=Class, y=relabund, fill=fenton))+
  geom_bar(stat="identity", position = position_dodge(width=0.7),width=0.5, 
           alpha=0.8,color="black",size=0.7)+
#  scale_fill_manual(values = c("#B35806","#542788"))+
#  scale_fill_manual(values = c("#F1A340","#998EC3"))+
#  scale_fill_manual(values = c("grey80","darkblue"))+
    scale_fill_manual(values = soil_palette("redox",2),
                      breaks = c("PreFenton", "PostFenton"))+

  ylab("% of total sorbed peaks")+
  xlab("")+

  theme_bw()+
  theme_kp()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, face="plain", size = 12))+
  theme(legend.position = c(0.8, 0.8))+
  guides(colour = guide_legend(override.aes = list(alpha = 1)))

```




