---
title: "4-misc_markdown"
author: "Kaizad Patel"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/markdown-fticr2/"
)
source("code/0-packages.R")
theme_set(theme_bw())
```

more FTICR rabbit-holing

---

# FTICR domains

1. classes

```{r domains_classes, fig.height=5, fig.width=7}
meta = read.csv(FTICR_META)

gg_vankrev(meta, aes(x = OC, y = HC, color = Class))+
  scale_color_manual(values = PNWColors::pnw_palette("Sailboat"))
```

2. DBE

```{r domains_dbe, fig.height=5, fig.width=7}
gg_vankrev(meta, aes(x = OC, y = HC, color = as.factor(DBE)))

```

3. NOSC

```{r domains_nosc, fig.height=5, fig.width=5}
gg_vankrev(meta, aes(x = OC, y = HC, color = NOSC))

```


# NOSC and O/C

```{r fenton_nosc_files}
fenton_loss = read.csv(FENTON_LOSS)

loss = fenton_loss %>% 
  filter(loss %in% c("lost", "gained")) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class),  by = "Mass")

fent = read.csv("fticr/fticr_master_hcoc.csv")
fenton = 
  fent %>% 
  filter(Treatment %in% c("PreFenton", "PostFenton")) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class),  by = "Mass")

fenton2 = 
  fenton %>% 
  group_by(Mass, Forest, Treatment) %>% 
  dplyr::summarize(n = n()) %>% 
  ungroup %>% 
  group_by(Treatment,Mass) %>% 
  dplyr::summarize(n = n()) %>% 
  ungroup %>% 
  group_by(Treatment, n) %>% 
  dplyr::summarise(count = n())

```

## NOSC for Fenton

```{r fenton_nosc, fig.width=8, fig.height=5}
fenton_nosc = 
  fenton %>%
  distinct(Treatment, Mass) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class),  by = "Mass") %>% 
  ggplot()+
  geom_histogram(aes(x = NOSC, fill = Treatment), position = "identity", alpha = 0.5)

fenton_oc = 
  fenton %>%
  distinct(Treatment, Mass) %>% 
  left_join(dplyr::select(meta, Mass, NOSC, Class, HC, OC),  by = "Mass") %>% 
  ggplot()+
  geom_histogram(aes(x = OC, fill = Treatment), position = "identity", alpha = 0.5)


library(patchwork)

fenton_nosc + fenton_oc +
  plot_layout(guides = "collect") +
  plot_annotation(title = "oxidation states",
                  subtitle = "combined for HW and SW")

```


## calculating NOSC of Fenton-lost and gained molecules

1. all lost and gained -- by forest

```{r}
ggplot(loss, aes(x = NOSC, color = loss, fill = loss))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(~Forest)
```

2. carbs and lignins

```{r}
loss_subset = 
  loss %>% 
  filter(Class %in% c("Carbohydrate-like","Lignin-like"))

ggplot(loss_subset)+
  geom_boxplot(aes(x = NOSC, y=80, color = loss),  width = 10)+
  geom_histogram(aes(x = NOSC, color = loss, fill = loss),
                 alpha = 0.5, position = "identity")

```


3. lignin only

```{r}

ggplot(loss[loss$Class=="Lignin-like",], aes(x = NOSC, color = loss, fill = loss))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=80, color = loss), fill = "white",  width = 10)

#facet_grid(~Forest)


ggplot(fenton[fenton$Class=="Lignin-like",])+
  geom_boxplot(aes(x = OC, y=150, color = Treatment),  width = 10)+
  geom_histogram(aes(x = OC, color = Treatment, fill = Treatment),
                 alpha = 0.5, position = "identity")

```


4. calculating NOSC of adsorbed molecules

```{r}
adsorbed = read.csv(GOETHITE_ADSORPTION)
adsorbed_nosc = adsorbed %>% 
  left_join(dplyr::select(meta, Mass, NOSC),  by = "Mass")

adsorbed_subset = 
  adsorbed_nosc %>% 
  filter(Class %in% c("Carbohydrate-like","Lignin-like"),
         adsorbed %in% c("sorbed"))
#dplyr::mutate(fenton = factor(fenton, levels = c("PreFenton", "PostFenton")))


ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=100, color = fenton),  fill = "white", width = 10)+
  ggtitle("adsorbed")+
  facet_wrap(~Class)

ggplot(adsorbed_subset, aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(binwidth = 0.05, alpha = 0.7, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=70, color = fenton),  fill = "white", width = 10)+
  
  scale_fill_manual(values = soil_palette("redox",2), guide = guide_legend(reverse=TRUE))+
  scale_color_manual(values = soil_palette("redox",2), guide = guide_legend(reverse=TRUE))+
  
  facet_wrap(~Class)+
  theme_kp()
```

```{r}

ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(.~Forest)

ggplot(adsorbed_subset, aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  facet_grid(Class~Forest)

ggplot(adsorbed_subset, aes(y = NOSC, x = "", color = fenton))+
  geom_boxplot()+
  facet_grid(Class~Forest)

ggplot(adsorbed_nosc[adsorbed_nosc$adsorbed=="sorbed",], aes(x = NOSC, color = fenton, fill = fenton))+
  geom_histogram(alpha = 0.5, position = "identity")+
  geom_boxplot(aes(x = NOSC, y=150, color = fenton),  fill = "white", width = 10)+
  ggtitle("adsorbed")
```



## combining fenton and goethite
```{r}
# set order of levels
adsorbed %>% 
  group_by(Mass,fenton,adsorbed, HC, OC, Class) %>% 
  dplyr::summarise(n = n()) %>% 
  ungroup %>% 
  dplyr::mutate(fenton=factor(fenton, levels = c("PreFenton","PostFenton")))->sorbed

```


adsorbed peaks common to pre and post-Fenton

```{r, fig.width=6, fig.height=6}
sorbed3 = 
  sorbed %>% 
  filter(adsorbed=="sorbed") %>% 
  group_by(Mass,fenton,adsorbed, HC, OC, Class) %>% 
  dplyr::summarise(n = n())  %>% 
  ungroup %>% 
  group_by(Mass, HC, OC) %>% 
  dplyr::mutate(common="common",
                unique = n(),
                unique2 = case_when(unique==1 ~ fenton,
                                    unique==2 ~ as.factor(common)))


gg_vankrev(sorbed3, aes(x = OC, y = HC, color=unique2))+
  labs(title = "adsorbed peaks common to pre and post-Fenton")+
  # scale_color_manual(values = c("#F1A340","#998EC3"))+
  # scale_color_manual(values = c("grey40","darkblue"))+
  #facet_wrap(~fenton)+
  theme_kp()

```

Fenton-gained peaks vs. adsorbed

```{r postfenton_newadsorbed, fig.height=5, fig.width=5}
fenton_loss %>% 
  filter(loss == "gained") %>% 
  gg_vankrev(aes(x = OC, y = HC))+
  geom_point(data = 
               adsorbed %>% 
               filter(fenton=="PostFenton" & adsorbed == "sorbed"), color = "orange")+
  labs(title = "Post-Fenton adsorbed peaks",
       subtitle = "new peaks in grey, adsorbed peaks in orange")+
  theme_kp()+
  NULL

```

# FTICR spectra

```{r}
rawmasterlong = read.csv(FTICR_RAWMASTER_LONG) %>% 
  group_by(Forest, Treatment, Fenton, Goethite, Mass) %>% 
  dplyr::summarise(intensity = mean(intensity)) %>% 
  ungroup %>% 
  mutate(Fenton = factor(Fenton, levels = c("PreFenton", "PostFenton")),
         Goethite = factor(Goethite, levels = c("PreGoethite", "PostGoethite")))

```

```{r}
library(scales)
rawmasterlong %>% 
  ggplot(aes(x = Mass, xend = Mass, y = 0, yend = intensity/1000000))+
  geom_segment(alpha = 0.5, size = 0.5)+
  scale_color_manual(values = soil_palette("podzol",2))+

  scale_y_continuous(limits = c(0,100), oob = rescale_none, label = comma)+
  labs(y = expression("intensity (x 10" ^6 *")"),
       x = "m/z")+
  facet_grid(Goethite ~ Fenton)+
  theme_kp()+
  NULL
```

